apigatewayv2:
  enabled: false
applicationautoscaling:
  enabled: false
cloudfront:
  enabled: false
cloudtrail:
  enabled: false
documentdb:
  enabled: false
dynamodb:
  enabled: false
ec2:
  enabled: false
ecr:
  enabled: false
ecs:
  enabled: false
efs:
  enabled: false
eks:
  enabled: false
elbv2:
  enabled: false
emrcontainers:
  enabled: false
eventbridge:
  enabled: false
iam:
  enabled: false
keyspaces:
  enabled: false
kms:
  enabled: false
lambda:
  enabled: false
memorydb:
  enabled: false
opensearchservice:
  enabled: false
pipes:
  enabled: false
prometheusservice:
  enabled: false
rds:
  enabled: false
s3:
  enabled: false
sagemaker:
  enabled: false
sfn:
  enabled: false
sns:
  enabled: false
sqs:
  enabled: false
